### ISSUE TITLE
Release URLs on tratt.net are 404'ing

### ISSUE THREAD

**Issue by chrisdickinson** [softdevteam/snare#107]
Hi! Thanks for this excellent project. I just noticed that the release URLs on [tratt.net](https://tratt.net/laurie/src/snare/releases/) seem to 404 & wanted to bring this to your attention!

**Comment by ltratt** [comment]
I am an idiot -- I scripted the building release pages, tried to cope with the variety of extensions that different projects have, and introduced a silly bug while doing so. It should be fixed now -- thank you for pointing this out!
