### ISSUE TITLE
OpenBSD package

### ISSUE THREAD

**Issue by netstx** [softdevteam/snare#88]
I just discovered snare and shortly after realized it's available as an OpenBSD package.

I was wondering if there's still time to bump it from 0.4.0 to 0.4.2 prior to OpenBSD 6.9 release. The main reason being the memory usage issue fixed in 0.4.1. 

Thanks for snare and also thanks for maintaining the OpenBSD package!

**Comment by ltratt** [comment]
Good news :) 0.4.2 is in ports as of a week or two back https://marc.info/?l=openbsd-ports-cvs&m=161653325128869&w=2

**Comment by netstx** [comment]
@ltratt That's awesome, thanks!
