### ISSUE TITLE
Github Webhook receives response code '200', but commands are not executed

### ISSUE THREAD

**Issue by netstx** [softdevteam/snare#89]
Hello again.

I am currently testing snare on OpenBSD 6.8 (pkg_add snare, v0.4.0) and although it looks like the snare process is sending responses to the webhook POST request, the command doesn't seem to execute (or perhaps it does, but it must fail).

I tested a push commit with wrong secret in the webhook configuration and did see snare logged it to /var/log/messages. I am wondering if there are some default OpenBSD security settings that may be causing the command to not execute.

Any thoughts? 

/etc/snare/snare.conf
```
listen = "0.0.0.0:8011";

github {
  match ".*" {
    cmd = "/etc/snare/%o/%r %e %j";
    errorcmd = "cat %s | mailx -s \"snare error: github.com/%o/%r\" my@email.com";
    secret = "random_secret";
  }
}
```

I also tested snare via 'snare -d -c /etc/snare/snare.conf' and didn't see any output after a post request was sent from github webhooks. I also tried 'user = "root";' in the config file for troubleshooting and also didn't get any output to stdout. 

The executable file in the cmd path is just a sh script that I created for testing. I recursively set ownership of /etc/snare/ to _snare:_snare just in case it was a permissions issue.

**Comment by ltratt** [comment]
> I tested a push commit with wrong secret in the webhook configuration 

I might not have understood your example correctly, but if the secret is incorrect, snare will refuse to execute anything, because it assumes you're being attacked by someone nefarious.

**Comment by netstx** [comment]
@ltratt Sorry for the confusion. Using the "wrong"  secret in the webhook configuration was just a test to see if I'd get any error messages or logs (which I did), so it tells me that snare is working and accepting post requests, but I have not figure out yet why the command (shell script) isn't being executed.

**Comment by ltratt** [comment]
It might help to run `snare` with `-d` so that it doesn't daemonise. You might find out what's going on that way. Alternatively, it rarely hurts to start `cmd` with `/bin/sh` just to make sure the shell is being run!

**Comment by netstx** [comment]
I tried using the -d flag, and then pushing a commit, but had no output. I am going to change the command to include /bin/sh and see if it helps :)

**Comment by ltratt** [comment]
If that doesn't work, maybe try something simple like `cmd="touch /tmp/test"` and see if that works. If it doesn't, something is going very wrong. If it does, then it might be that you can start to narrow down your problem.

**Comment by netstx** [comment]
@ltratt  ok, so using /bin/sh to start `cmd` didn't seem to work, but using `cmd="touch /tmp/test" did. That's an easy way to test it! I ran snare with -d during these two tests and neither displayed output, not sure if that is expected.

I guess I need to figure out why shell scripts aren't being executed. It must be something permission related.

**Comment by netstx** [comment]
Yep! Thanks again for your time, I appreciate it!

**Comment by netstx** [comment]
Update: looks like I need to use absolute paths in the shell script called by `cmd`. Didn't necessarily have to use /bin/sh -c '/path/to/prps/%o/%r %e %j'
